model_params:  
  descrip: "Everything Good, Feature Loss implemented"
  model_name: "DeepDive"
  mode: "Train"
  log_dir: /media/mnt/dehaze/logs/

training_params:
  learning_rate: 1e-05
  epochs: 5000
  batch_size: 32
  data_path: /media/mnt/dehaze/npy_files/
