model_params:  
  descrip: "Building Graph"
  model_name: "MSCNN" # DD or MSCNN
  mode: "test"   # train or test
  log_dir: /media/mnt/dehaze/logs/ # path to write the model and load the model

training_params:
  learning_rate: 1e-04
  epochs: 250
  batch_size: 32
  data_path: /media/mnt/dehaze/data/ChinaMM18dehaze/  # Path from where to load the data
